apiVersion: apps/v1
kind: Deployment
metadata:
    name: employee-deployment
    labels:
        app: hotelup
    namespace: hotelup
spec:
    replicas: 1
    selector:
        matchLabels:
            app: employee
    template:
        metadata:
            name: employee
            labels:
                app: employee
        spec:
            containers:
                - name: employee
                  image: wiaz/hotelup.employee:latest
                  imagePullPolicy: Always
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: Production
                  ports:
                      - containerPort: 8080
                        protocol: TCP
                  volumeMounts:
                      - name: aws-credentials
                        mountPath: /home/app/.aws
            restartPolicy: Always
            volumes:
                - name: aws-credentials
                  secret:
                      secretName: aws-credentials
---
apiVersion: v1
kind: Service
metadata:
    name: employee-service
    labels:
        app: employee
    namespace: hotelup
spec:
    selector:
        app: employee
    ports:
        - protocol: TCP
          port: 5002
          targetPort: 8080
    type: ClusterIP
